#!/usr/bin/env bash
#  Display "Best School" 10 times, but for the 9th iteration, display
#+ "Best School" and then "Hi" on a new line

i=0
string="Best School"

while [[ "$i" -lt 10 ]];
do
	if [ "$i" -eq 8 ];
	then
		echo "$string"
		echo "Hi";
	else
		echo "$string";
	fi
	: $(( i++ ))
done
