#!/usr/bin/env bash
# display the time for 12 hours and 59 minutes
# display the hours from 0 to 12
# display minutes from 1 to 59

hour=0
min=1

while [[ "$hour" -lt 13 ]];
do
	echo "Hour: $hour"
	while [[ "$min" -lt 60 ]];
	do
		echo "$min"
		(( min++ ))
	done
	(( min = 1 ))
	: $(( hour++ ))
done
